DELETE FROM products 

TRUNCATE TABLE products RESTART IDENTITY;

DELETE FROM stock WHERE product_id IN (SELECT id FROM products);

TRUNCATE TABLE products RESTART IDENTITY;

TRUNCATE TABLE products RESTART IDENTITY;

TRUNCATE TABLE products, stock RESTART IDENTITY CASCADE;

